import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="" />
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About Us</Link>
        </nav>
      </header>
      <main>
        {data.map((ev) => (
          <Link key={ev.id} href={`/events/${ev.id}`}>
            <h2>{ev.title}</h2>
            <Image src={ev.image} width="300" height="300" alt={ev.id} />

            <p>{ev.description}</p>
          </Link>
        ))}
      </main>
    </>
  );
}
export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");

  console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
